### ISSUE TITLE
Keep Identity

### ISSUE THREAD

**Issue by schmiz** [gtaylor44/SqlBulkTools#44]
Is it possible to configure the BulkInsertOrUpdate to keep the source Identity? I know that the SqlBulkCopy allows a setting of System.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity but I don't see this implemented in the SqlBulkTools.

**Comment by gtaylor44** [comment]
This is currently supported.. Example:

```
            using (TransactionScope trans = new TransactionScope())
            {
                using (SqlConnection conn = new SqlConnection(ConfigurationManager
                    .ConnectionStrings["SqlBulkToolsTest"].ConnectionString))
                {
                    bulk.Setup<Book>()
                            .ForCollection(bookList)
                            .WithTable("Books")
                            .WithBulkCopySettings(new BulkCopySettings()
                            {
                               SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity
                            })
                            .AddAllColumns()
                            .BulkInsertOrUpdate()
                            .MatchTargetOn(x => x.ISBN)
                            .SetIdentityColumn(x => x.Id, ColumnDirectionType.InputOutput)
                            .Commit(conn);
                }
                trans.Complete();
            }
```

**Comment by schmiz** [comment]
Thank you for your quick response. I have my setup as follows but the inserted records receive a new ID generated from the destination table identity instead of using the source ID as the value.

```c#
new BulkOperations()
                            .Setup<DistrictMembership>()
                            .ForCollection(DistrictMembership.QuerySource(request.ReportID))
                            .WithTable(typeof(DistrictMembership).GetCustomAttribute<TableAttribute>().Name)
                            .WithSchema(typeof(DistrictMembership).GetCustomAttribute<TableAttribute>().Schema)
                            .WithBulkCopySettings(new BulkCopySettings()
                            {
                                //BatchSize = 5000,
                                BulkCopyTimeout = 0, // Default is 600 seconds
                                EnableStreaming = true,
                                SqlBulkCopyOptions = System.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity
                                //SqlBulkCopyOptions = SqlBulkCopyOptions.TableLock
                            })
                            .AddAllColumns()
                            .BulkInsertOrUpdate()
                            .SetIdentityColumn(x => x.DISTRICT_MEMBERSHIP_ID, SqlBulkTools.Enumeration.ColumnDirectionType.InputOutput)
                            .MatchTargetOn(x => x.DISTRICT_MEMBERSHIP_ID)
                            .Commit(conn);
```

**Comment by gtaylor44** [comment]
After some thought I have realised that BulkInsertOrUpdate will not be compatible with KeepIdentity. BulkInsertOrUpdate will insert records into a temp table using KeepIdentity then attempt to merge into actual target. 

KeepIdentity will only work for BulkInsert at this time and you should omit SetIdentityColumn (because it ignores inserting the column). 

```
        [TestMethod]
        public void SqlBulkTools_BulkInsert_KeepIdentity()
        {
            var bulk = new BulkOperations();
            List<Book> bookList = new List<Book>();

            for (int i = 0; i < 30; i++)
            {
                bookList.Add(new Book
                {
                    Id = i + 5000000,
                    Description = "Some desc",
                    Price = 450.23M,
                    ISBN = "1234567891234"
                });
            }

            using (TransactionScope trans = new TransactionScope())
            {
                using (SqlConnection conn = new SqlConnection(ConfigurationManager
                    .ConnectionStrings["SqlBulkToolsTest"].ConnectionString))
                {
                    bulk.Setup<Book>()
                        .ForDeleteQuery()
                        .WithTable("Books")
                        .Delete()
                        .AllRecords()
                        .Commit(conn);

                    bulk.Setup<Book>()
                        .ForCollection(bookList)
                        .WithTable("Books")
                        .WithBulkCopySettings(new BulkCopySettings()
                        {
                            SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity
                        })
                        .AddAllColumns()
                        .BulkInsert()
                        .Commit(conn);
                }

                trans.Complete();
            }

            Assert.IsTrue(_dataAccess.GetBookList().First().Id == 5000000);
        }
```

**Comment by gtaylor44** [comment]
I've added support for KeepIdentity when using BulkInsertOrUpdate.

Please update to version **4.49**

Your previous example should work now. Note that SetIdentityColumn will still be **required**. If you were using BulkInsert you can omit SetIdentityColumn as previously stated. 

```
new BulkOperations()
                            .Setup<DistrictMembership>()
                            .ForCollection(DistrictMembership.QuerySource(request.ReportID))
                            .WithTable(typeof(DistrictMembership).GetCustomAttribute<TableAttribute>().Name)
                            .WithSchema(typeof(DistrictMembership).GetCustomAttribute<TableAttribute>().Schema)
                            .WithBulkCopySettings(new BulkCopySettings()
                            {
                                //BatchSize = 5000,
                                BulkCopyTimeout = 0, // Default is 600 seconds
                                EnableStreaming = true,
                                SqlBulkCopyOptions = System.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity
                                //SqlBulkCopyOptions = SqlBulkCopyOptions.TableLock
                            })
                            .AddAllColumns()
                            .BulkInsertOrUpdate()
                            .SetIdentityColumn(x => x.DISTRICT_MEMBERSHIP_ID, SqlBulkTools.Enumeration.ColumnDirectionType.InputOutput)
                            .MatchTargetOn(x => x.DISTRICT_MEMBERSHIP_ID)
                            .Commit(conn);
```
Just a suggestion... Do you really need ColumnDirectionType.InputOutput on identity column if the source already contains the value for DISTRICT_MEMBERSHIP_ID?

**Comment by schmiz** [comment]
Great! Thanks for looking into this. I updated to 4.49 and The BulkInsertOrUpdate is keeping the identity of the source. YAY!
Unfortunately the BulkInsert doesn't appear to work with KeepIdentity.
My setup is as follows...
```c#
new BulkOperations()
                            .Setup<GradeMembership>()
                            .ForCollection(GradeMembership.QuerySource(request.ReportID))
                            .WithTable(typeof(GradeMembership).GetCustomAttribute<TableAttribute>().Name)
                            .WithSchema(typeof(GradeMembership).GetCustomAttribute<TableAttribute>().Schema)
                            .WithBulkCopySettings(new BulkCopySettings()
                            {
                                //BatchSize = 5000,
                                BulkCopyTimeout = 0, // Default is 600 seconds
                                EnableStreaming = true,
                                SqlBulkCopyOptions = System.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity
                                //SqlBulkCopyOptions = SqlBulkCopyOptions.TableLock
                            })
                            .AddAllColumns()
                            .CustomColumnMapping(x => x.sec504_SERVICES, "504_SERVICES")
                            .BulkInsert()
                            .SetIdentityColumn(x => x.GRADE_MEMBERSHIP_ID)
                            .Commit(conn);
```

The exception thrown is `Violation of PRIMARY KEY constraint 'PK_GRADE_MEMBERSHIP'. Cannot insert duplicate key in object 'PSIS.GRADE_MEMBERSHIP'. The duplicate key value is (0).`

**Comment by schmiz** [comment]
I re-read your comments here and noticed you mentioned to remove the SetIdentityColumn on the BulkInsert. I removed it from the setup above but still get the same exception... `{"Violation of PRIMARY KEY constraint 'PK_GRADE_MEMBERSHIP'. Cannot insert duplicate key in object 'PSIS.GRADE_MEMBERSHIP'. The duplicate key value is (0).\r\nThe statement has been terminated."}`
 
I double checked the source and there are no records in the source with a value of 0 for the primary key

**Comment by gtaylor44** [comment]
I'm unable to reproduce this, the test for KeepIdentity and BulkInsert is passing. I do notice that this is a different table to your initial example.

- Can you check that there is no record in target that has a PK of 0
- If there is a record in the target with PK of 0 then validate source does not contain an ID with 0...
```
var col = GradeMembership.QuerySource(request.ReportID);
Assert.IsFalse(col.Any(x => x.GRADE_MEMBERSHIP_ID == 0));
```
- Triple check that all ids are unique...  
```
var col = GradeMembership.QuerySource(request.ReportID);
Assert.IsTrue(col.Select(x => x.GRADE_MEMBERSHIP_ID).Distinct().Count() == col.Count);
```

Let me know when you resolve.

**Comment by schmiz** [comment]
Many thanks! you were absolutely right. I had an incorrect type in the object and the collection didn't get populated correctly. The BulkInsertOrUpdate and BulkInsert are both respecting the KeepIdentity.

**Comment by gtaylor44** [comment]
Glad to see everything resolved. Cheers!
